# Generated by Django 5.2.13 on 2026-05-04 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Clase sin titulo', max_length=140)),
                ('mode', models.CharField(choices=[('free_manual', 'Gratis manual'), ('api', 'API')], default='free_manual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('prompt_ready', 'Prompt listo'), ('toon_ready', 'TOON listo'), ('verified', 'JSON/Verificacion lista'), ('error', 'Error')], default='draft', max_length=20)),
                ('source_text', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, upload_to='audio/')),
                ('transcript', models.TextField(blank=True)),
                ('generation_prompt', models.TextField(blank=True)),
                ('toon_output', models.TextField(blank=True)),
                ('verification_prompt', models.TextField(blank=True)),
                ('verification_output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Gratis'), ('basic', 'Basico API'), ('pro', 'Pro API'), ('unlimited', 'Ilimitado API')], default='free', max_length=20)),
                ('api_classes_used', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
