# Generated by Django 5.2.13 on 2026-05-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonjob',
            name='corrected_output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonjob',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('prompt_ready', 'Prompt listo'), ('toon_ready', 'Ítems listos'), ('verified', 'Verificación lista'), ('corrected', 'Corregido y listo'), ('error', 'Error')], default='draft', max_length=20),
        ),
    ]
