# Generated by Django 5.2.13 on 2026-05-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_add_corrected_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonjob',
            name='share_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lessonjob',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privada'), ('shared', 'Compartida con link'), ('public', 'Pública en explorar')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_goal',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_study_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
