# Generated by Django 5.2.13 on 2026-05-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_processing_queue_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonjob',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('queued', 'En cola'), ('processing', 'Procesando'), ('prompt_ready', 'Prompt listo'), ('toon_ready', 'Ítems listos'), ('verified', 'Verificación lista'), ('corrected', 'Corregido y listo'), ('error', 'Error')], default='draft', max_length=20),
        ),
    ]
