# Generated by Django 5.2.13 on 2026-05-08 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_mini_coherence_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=40)),
                ('bloom_level', models.CharField(choices=[('L1', 'Recordar'), ('L2', 'Comprender'), ('L3', 'Aplicar'), ('L4', 'Analizar'), ('L5', 'Evaluar'), ('L6', 'Crear')], default='L1', max_length=2)),
                ('topic', models.CharField(blank=True, max_length=180)),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=12)),
                ('irt_a', models.FloatField(default=1.0)),
                ('irt_b', models.FloatField(default=0.0)),
                ('irt_c', models.FloatField(default=0.25)),
                ('source_timestamp_seconds', models.FloatField(blank=True, null=True)),
                ('source_excerpt', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('academic_period', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('instructor', models.CharField(blank=True, max_length=160)),
                ('main_topics', models.JSONField(blank=True, default=list)),
                ('level', models.CharField(choices=[('introductory', 'Introductorio'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='introductory', max_length=20)),
                ('student_goal', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('media_file', models.FileField(blank=True, upload_to='classes/')),
                ('class_date', models.DateField(blank=True, null=True)),
                ('main_topic', models.CharField(blank=True, max_length=180)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('waiting_confirmation', 'Esperando confirmacion'), ('queued', 'En cola'), ('processing', 'Procesando'), ('ready', 'Lista'), ('error', 'Error')], default='draft', max_length=32)),
                ('requested_outputs', models.JSONField(blank=True, default=list)),
                ('estimated_credit_cost', models.IntegerField(default=0)),
                ('confirmed_credit_cost', models.IntegerField(default=0)),
                ('processing_log', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_lesson_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_session', to='learning.lessonjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='learning.course')),
            ],
            options={
                'ordering': ['-class_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdaptiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theta', models.FloatField(default=0.0)),
                ('standard_error', models.FloatField(default=9.99)),
                ('mastery_by_topic', models.JSONField(blank=True, default=dict)),
                ('bloom_mastery', models.JSONField(blank=True, default=dict)),
                ('weak_topics', models.JSONField(blank=True, default=list)),
                ('strong_topics', models.JSONField(blank=True, default=list)),
                ('recommended_difficulty', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=12)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_profiles', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_profiles', to='learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('plan_grant', 'Creditos de plan'), ('class_transcription', 'Transcripcion de clase'), ('summary_generation', 'Generacion de resumen'), ('flashcard_generation', 'Generacion de flashcards'), ('quiz_generation', 'Generacion de quiz'), ('adaptive_evaluation', 'Evaluacion adaptativa'), ('regeneration', 'Regeneracion'), ('manual_adjustment', 'Ajuste manual')], max_length=32)),
                ('amount', models.IntegerField(help_text='Positive grants credits; negative amounts consume credits.')),
                ('balance_after', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='learning.classsession')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='learning.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=180)),
                ('difficulty', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=12)),
                ('source_timestamp_seconds', models.FloatField(blank=True, null=True)),
                ('source_excerpt', models.TextField(blank=True)),
                ('mastery_level', models.PositiveSmallIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='learning.classsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='learning.course')),
            ],
            options={
                'ordering': ['topic', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('topic', models.CharField(blank=True, max_length=180)),
                ('quiz_type', models.CharField(choices=[('practice', 'Practica'), ('adaptive', 'Adaptativo'), ('diagnostic', 'Diagnostico')], default='adaptive', max_length=20)),
                ('bloom_distribution', models.JSONField(blank=True, default=dict)),
                ('cat_config', models.JSONField(blank=True, default=dict)),
                ('mini_source', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='learning.classsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='learning.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.quiz'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('dismissed', 'Descartada')], default='pending', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='learning.classsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='learning.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'priority', 'due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('theta_before', models.FloatField(blank=True, null=True)),
                ('theta_after', models.FloatField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='learning.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='learning.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='learning.quiz')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_answers', to='learning.answeroption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-answered_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('class_uploaded', 'Clase subida'), ('summary_reviewed', 'Resumen revisado'), ('flashcards_reviewed', 'Flashcards repasadas'), ('quiz_completed', 'Quiz completado'), ('errors_reviewed', 'Errores revisados'), ('recommendation_done', 'Recomendacion completada')], max_length=32)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('study_seconds', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_activities', to='learning.classsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_activities', to='learning.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('longest_count', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('brief', 'Breve'), ('structured', 'Estructurado'), ('course_accumulated', 'Acumulado del curso')], default='brief', max_length=32)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('content', models.TextField()),
                ('key_concepts', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='learning.classsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='learning.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField()),
                ('source', models.CharField(choices=[('whisper', 'Whisper'), ('manual', 'Manual'), ('imported', 'Importada')], default='whisper', max_length=20)),
                ('language', models.CharField(default='es', max_length=12)),
                ('average_confidence', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_record', to='learning.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.FloatField(default=0)),
                ('end_seconds', models.FloatField(default=0)),
                ('text', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=180)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='learning.transcript')),
            ],
            options={
                'ordering': ['order', 'start_seconds'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['user', 'is_archived'], name='learning_co_user_id_f0c25e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='learning_co_name_c6a9e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'academic_period'), name='unique_course_per_user_period'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['user', 'status'], name='learning_cl_user_id_e6ebaa_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['course', 'status'], name='learning_cl_course__4871f9_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['class_date'], name='learning_cl_class_d_defbfd_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptiveprofile',
            index=models.Index(fields=['user', 'course'], name='learning_ad_user_id_12d49c_idx'),
        ),
        migrations.AddConstraint(
            model_name='adaptiveprofile',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_adaptive_profile_per_course'),
        ),
        migrations.AddIndex(
            model_name='creditledgerentry',
            index=models.Index(fields=['user', 'created_at'], name='learning_cr_user_id_4abf95_idx'),
        ),
        migrations.AddIndex(
            model_name='creditledgerentry',
            index=models.Index(fields=['course', 'created_at'], name='learning_cr_course__36e969_idx'),
        ),
        migrations.AddIndex(
            model_name='creditledgerentry',
            index=models.Index(fields=['action'], name='learning_cr_action_7cafab_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['course', 'topic'], name='learning_fl_course__d0eda4_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['next_review_at'], name='learning_fl_next_re_e6203f_idx'),
        ),
        migrations.AddIndex(
            model_name='answeroption',
            index=models.Index(fields=['question', 'is_correct'], name='learning_an_questio_6b229a_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', 'quiz_type'], name='learning_qu_course__78d3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['class_session', 'quiz_type'], name='learning_qu_class_s_eef6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='learning_qu_quiz_id_eeeb66_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['bloom_level'], name='learning_qu_bloom_l_3eaeea_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic'], name='learning_qu_topic_ca363c_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'status'], name='learning_re_user_id_fc2a59_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['course', 'status'], name='learning_re_course__f33822_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['due_at'], name='learning_re_due_at_892053_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['user', 'course', 'answered_at'], name='learning_st_user_id_4d999a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['quiz', 'answered_at'], name='learning_st_quiz_id_d83a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='studyactivity',
            index=models.Index(fields=['user', 'occurred_at'], name='learning_st_user_id_a99588_idx'),
        ),
        migrations.AddIndex(
            model_name='studyactivity',
            index=models.Index(fields=['course', 'occurred_at'], name='learning_st_course__739eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='studyactivity',
            index=models.Index(fields=['activity_type'], name='learning_st_activit_f9ec4d_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['course', 'kind'], name='learning_su_course__7ff220_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['class_session', 'kind'], name='learning_su_class_s_ee2092_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['transcript', 'order'], name='learning_tr_transcr_3d99cf_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['topic'], name='learning_tr_topic_81b9ea_idx'),
        ),
    ]
