# Generated by Django 5.2.13 on 2026-05-08 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_question_course_classsession_adaptiveprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonjob',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_lesson_jobs', to='learning.course'),
        ),
    ]
