# Generated by Django 5.2.13 on 2026-05-08 05:36

from django.db import migrations, models


def seed_credit_balances(apps, schema_editor):
    Profile = apps.get_model("learning", "Profile")
    CreditLedgerEntry = apps.get_model("learning", "CreditLedgerEntry")
    plan_credits = {
        "free": 30,
        "basic": 600,
        "pro": 2200,
        "unlimited": None,
    }
    for profile in Profile.objects.select_related("user"):
        amount = plan_credits.get(profile.plan, 30)
        profile.credit_balance = 0 if amount is None else amount
        profile.save(update_fields=["credit_balance"])
        CreditLedgerEntry.objects.create(
            user=profile.user,
            action="plan_grant",
            amount=0 if amount is None else amount,
            balance_after=profile.credit_balance,
            description="Creditos iniciales migrados",
            metadata={"plan": profile.plan, "migration": "0013"},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_lessonjob_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(seed_credit_balances, migrations.RunPython.noop),
    ]
