# Generated by Django 5.2.13 on 2026-05-08 18:52

from django.db import migrations, models
from decimal import Decimal


def seed_plan_catalog(apps, schema_editor):
    PlanCatalog = apps.get_model("learning", "PlanCatalog")
    plans = [
        {
            "code": "free",
            "name": "Gratis",
            "description": "Sin API externa. Ideal para probar SIMA con creditos iniciales y flujo manual.",
            "monthly_price_usd": Decimal("0.00"),
            "monthly_api_classes": 0,
            "monthly_credits": 30,
            "api_enabled": False,
            "sort_order": 10,
        },
        {
            "code": "basic",
            "name": "Basico",
            "description": "Plan de entrada para clases API y materiales de estudio generados.",
            "monthly_price_usd": Decimal("5.00"),
            "monthly_api_classes": 6,
            "monthly_credits": 600,
            "api_enabled": True,
            "sort_order": 20,
        },
        {
            "code": "pro",
            "name": "Pro",
            "description": "Mas creditos y clases API para ciclos con mayor carga academica.",
            "monthly_price_usd": Decimal("10.00"),
            "monthly_api_classes": 20,
            "monthly_credits": 2200,
            "api_enabled": True,
            "sort_order": 30,
        },
        {
            "code": "unlimited",
            "name": "Ilimitado",
            "description": "Uso ilimitado para clases API, transcripcion y regeneraciones.",
            "monthly_price_usd": Decimal("25.00"),
            "monthly_api_classes": None,
            "monthly_credits": None,
            "api_enabled": True,
            "sort_order": 40,
        },
    ]
    for plan in plans:
        PlanCatalog.objects.update_or_create(code=plan["code"], defaults=plan)


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_profile_credit_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('free', 'Gratis'), ('basic', 'Basico API'), ('pro', 'Pro API'), ('unlimited', 'Ilimitado API')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('monthly_api_classes', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_credits', models.PositiveIntegerField(blank=True, null=True)),
                ('api_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price_usd', 'code'],
            },
        ),
        migrations.RunPython(seed_plan_catalog, migrations.RunPython.noop),
    ]
