# Generated by Django 5.2.13 on 2026-05-08 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_profile_daily_goals(apps, schema_editor):
    Profile = apps.get_model("learning", "Profile")
    UserPreference = apps.get_model("learning", "UserPreference")
    for profile in Profile.objects.select_related("user"):
        UserPreference.objects.update_or_create(
            user_id=profile.user_id,
            defaults={"daily_goal": profile.daily_goal},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_plancatalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_goal', models.PositiveIntegerField(default=10)),
                ('default_study_minutes', models.PositiveIntegerField(default=25)),
                ('preferred_language', models.CharField(choices=[('es', 'Espanol'), ('en', 'Ingles')], default='es', max_length=8)),
                ('theme', models.CharField(choices=[('system', 'Sistema'), ('light', 'Claro'), ('dark', 'Oscuro')], default='system', max_length=16)),
                ('email_reminders', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(copy_profile_daily_goals, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='profile',
            name='daily_goal',
        ),
    ]
