# Generated by Django 4.2.11 on 2026-09-05 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0016_lessonjob_backend_cloud"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "focus",
                    models.CharField(
                        choices=[
                            ("balanced", "Equilibrada"),
                            ("weak", "Refuerzo de temas debiles"),
                        ],
                        default="balanced",
                        max_length=16,
                    ),
                ),
                ("target_count", models.PositiveIntegerField(default=10)),
                ("theta_start", models.FloatField(default=0.0)),
                ("theta", models.FloatField(default=0.0)),
                ("standard_error", models.FloatField(default=9.99)),
                ("served_question_ids", models.JSONField(blank=True, default=list)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("feedback", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sessions",
                        to="learning.course",
                    ),
                ),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="learning.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="practice_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="learning.practicesession",
            ),
        ),
        migrations.AddIndex(
            model_name="practicesession",
            index=models.Index(
                fields=["user", "course", "completed_at"],
                name="learning_pr_user_id_01a95a_idx",
            ),
        ),
    ]
