# Generated by Django 4.2.11 on 2026-09-05 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0017_practice_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesession",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Si esta definido, la practica se limita al banco de esa clase.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="practice_sessions",
                to="learning.lessonjob",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="quiz_type",
            field=models.CharField(
                choices=[
                    ("practice", "Practica"),
                    ("adaptive", "Adaptativo"),
                    ("diagnostic", "Diagnostico"),
                    ("reinforcement", "Refuerzo"),
                ],
                default="adaptive",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="summary",
            name="kind",
            field=models.CharField(
                choices=[
                    ("brief", "Breve"),
                    ("structured", "Estructurado"),
                    ("course_accumulated", "Acumulado del curso"),
                    ("concept", "Explicacion de concepto"),
                ],
                default="brief",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ReinforcementJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topics", models.JSONField(blank=True, default=list)),
                ("theta", models.FloatField(default=0.0)),
                ("requested_items", models.PositiveIntegerField(default=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En cola"),
                            ("processing", "Procesando"),
                            ("done", "Listo"),
                            ("error", "Error"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("processing_log", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("summary_ids", models.JSONField(blank=True, default=list)),
                ("flashcard_ids", models.JSONField(blank=True, default=list)),
                ("credits_charged", models.IntegerField(default=0)),
                ("credits_refunded", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reinforcement_jobs",
                        to="learning.course",
                    ),
                ),
                (
                    "practice_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reinforcement_jobs",
                        to="learning.practicesession",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reinforcement_jobs",
                        to="learning.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reinforcement_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "course", "status"],
                        name="learning_re_user_id_aa434a_idx",
                    )
                ],
            },
        ),
    ]
