# Generated by Django 4.2.11 on 2026-09-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0018_reinforcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="ease_factor",
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="interval_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="last_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="repetitions",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
