# Generated by Django 4.2.11 on 2026-09-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0019_flashcard_sm2"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesession",
            name="prior_sd",
            field=models.FloatField(
                default=1.0,
                help_text="Desviacion del prior N(theta_start, prior_sd) usado por EAP.",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="b_calibrated",
            field=models.FloatField(
                blank=True,
                help_text="Dificultad corregida con respuestas reales (Elo).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="calibration_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="quality_flag",
            field=models.CharField(
                blank=True, help_text="'' | too_easy | suspect", max_length=16
            ),
        ),
    ]
