# Generated by Django 4.2.11 on 2026-09-05 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0020_engine_v2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicesession",
            name="focus",
            field=models.CharField(
                choices=[
                    ("balanced", "Equilibrada"),
                    ("weak", "Refuerzo de temas debiles"),
                    ("risk", "Repaso de temas en riesgo de olvido"),
                    ("exam", "Simulacro"),
                ],
                default="balanced",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="SummaryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("class", "Resumen de clase"),
                            ("course", "Resumen del curso"),
                        ],
                        default="class",
                        max_length=12,
                    ),
                ),
                ("backend", models.CharField(default="auto", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En cola"),
                            ("processing", "Procesando"),
                            ("done", "Listo"),
                            ("error", "Error"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("processing_log", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("credits_charged", models.IntegerField(default=0)),
                ("credits_refunded", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_jobs",
                        to="learning.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_jobs",
                        to="learning.lessonjob",
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="learning.summary",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "course", "status"],
                        name="learning_su_user_id_4a4140_idx",
                    )
                ],
            },
        ),
    ]
