# Generated by Django 4.2.11 on 2026-09-05 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0021_summary_job_focus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizresponse",
            name="attempt",
        ),
        migrations.DeleteModel(
            name="QuizAttempt",
        ),
        migrations.DeleteModel(
            name="QuizResponse",
        ),
    ]
