# Generated by Django 4.2.11 on 2026-09-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0022_drop_legacy_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="exam_date",
            field=models.DateField(
                blank=True,
                help_text="Proxima evaluacion: activa la cuenta regresiva y el simulacro en el plan.",
                null=True,
            ),
        ),
    ]
