from django.contrib.auth import views as auth_views
from django.urls import path

from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("mini", views.mini_landing, name="mini_landing"),
    path("mini/", views.mini_landing, name="mini_landing_slash"),
    path("mini/benchmark/", views.mini_benchmark, name="mini_benchmark"),
    path("registro/", views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("cursos/nuevo/", views.course_create, name="course_create"),
    path("cursos/<int:pk>/", views.course_detail, name="course_detail"),
    path("cursos/<int:pk>/practicar/", views.practice_start, name="practice_start"),
    path("cursos/<int:pk>/practica/<int:session_id>/", views.practice_session, name="practice_session"),
    path("cursos/<int:pk>/practica/<int:session_id>/responder/", views.practice_answer, name="practice_answer"),
    path("cursos/<int:pk>/recomendaciones/<int:rec_id>/", views.recommendation_update, name="recommendation_update"),
    path("cursos/<int:pk>/refuerzo/", views.reinforcement_start, name="reinforcement_start"),
    path("cursos/<int:pk>/refuerzo/<int:job_id>/", views.reinforcement_detail, name="reinforcement_detail"),
    path("cursos/<int:pk>/repasar/", views.course_review, name="course_review"),
    path("cursos/<int:pk>/repasar/tarjeta/", views.course_review_card, name="course_review_card"),
    path("planes/", views.plans, name="plans"),
    path("gratis/nueva/", views.free_lesson, name="free_lesson"),
    path("api/nueva/", views.api_lesson, name="api_lesson"),
    path("clase/<int:pk>/", views.lesson_detail, name="lesson_detail"),
    path("clase/compartida/<str:token>/", views.shared_lesson_detail, name="shared_lesson_detail"),
    path("clase/<int:pk>/estado/", views.lesson_job_status, name="lesson_job_status"),
    path("clase/<int:pk>/reintentar/", views.retry_api_lesson, name="retry_api_lesson"),
    path("clase/<int:pk>/quiz/iniciar/", views.start_quiz, name="start_quiz"),
    path("clase/<int:pk>/toon/", views.submit_toon, name="submit_toon"),
    path("clase/<int:pk>/verificacion/", views.submit_verification, name="submit_verification"),
    path("clase/<int:pk>/transcripcion/", views.repair_transcript, name="repair_transcript"),
    path("clase/<int:pk>/coherencia/", views.repair_coherence, name="repair_coherence"),
    path("clase/<int:pk>/visibilidad/", views.set_visibility, name="set_visibility"),
    path("clase/<int:pk>/renombrar/", views.rename_lesson, name="rename_lesson"),
    path("clase/<int:pk>/eliminar/", views.delete_lesson, name="delete_lesson"),
    path("clase/<int:pk>/descargar/", views.download_json, name="download_json"),
    path("clase/<int:pk>/flashcards/", views.flashcards, name="flashcards"),
    path("clase/<int:pk>/flashcards/repasar/", views.review_flashcard, name="review_flashcard"),
    path("clase/<int:pk>/mapa/", views.class_map, name="class_map"),
    path("clase/<int:pk>/ejercicios/emparejar/", views.matching_exercise, name="matching_exercise"),
    path("clase/<int:pk>/ejercicios/completar/", views.cloze_exercise, name="cloze_exercise"),
    path("clase/<int:pk>/pipeline/", views.pipeline_visualization, name="pipeline_visualization"),
]
